name: 🌸 Style
description: Report a styling problem
title: "Style: <title>"
labels: [style, needs triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you have encountered.
    options:
    - label: There are no matching existing issues
      required: true
- type: textarea
  attributes:
    label: Error Source
    description: In what branch did you find this error?
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing. Note where behavior is not matching your expected output.
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution
    description: |
      Is there a solution that you have in mind? Or, do you have an idea why the styling issue exists?
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Please describe the environment you are finding this error in.
      examples:
        - **OS**: Pixel 4 Emulator
        - **System Image**: Oreo (Api Level 27, ABI x86)
        - **Screen Resolution**: 1080 x 2280
    value: |
      - OS:
      - System Image:
      - Screen Resolution:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots/ Files
    description: |
      Images of the styling issue are required to submit an issue.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Please confirm your process
    description: Make sure that you have followed basic steps before reporting an error.
    options:
    - label: I have reviewed all the documentation and my practices are consistent with the repo's requirements.
      required: true
    - label: I have done npm install to make sure I have all the required packages.
      required: true
    - label: I have done pip install -r requirements.txt so my backend is up to date.
      required: true